a = 42;
b = "Bonjour";
c = true;
d = null;
let e;
f = [1, 2, 3];
g = { nom: "Ali" };
h = NaN;
console.log( a + " -> " + typeof a); 
console.log( b + " -> " + typeof b); 
console.log( c + " -> " + typeof c); 
console.log( d + " -> " + typeof d); 
console.log( e + " -> " + typeof e); 
console.log( f + " -> " + typeof f); 
console.log( g + " -> " + typeof g); 
console.log( h + " -> " + typeof h);
